version: '3'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    restart: always
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-8501}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS:-0.0.0.0}
    # No volumes in production to use the code baked into the image
    healthcheck:
      test: ["CMD", "python", "healthcheck.py", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
